(setf *clk* "main_clk")
(setf *rstb* "main_rstb")
(push '("crc0"     "crc"     (slave ( "dev0" ) "c_"   #x14) (in "ack")) *place-list*)
(push '("hwtimer0" "hwtimer" (slave ( "dev0" ) "c_"    #xc) (in "fclk") (in "frstb") (out "irq")) *place-list*)
(push '("fclkdiv0" "fclkdiv" (slave ( "dev0" ) "c_"   #x10) (out "frstb") (out "fclk") (in "rstb") (in "clk") (in "scan_mode")) *place-list*)
(push '("cgu0"     "cgu"     (slave ( "dev0" ) "c_"   #x10) (out "lck" 3) (out "lrb" 3) (in "fclk" 3) (in "rtc" 31) (in "scan_mode")) *place-list*)
(push '("uart_rx0" "uart_rx" (slave ( "dev0" ) ""     #x14) (in  "rx") (out "cs") (out "cl") (out "irq") (in "frstb") (in "fclk")) *place-list*)
(push '("uart_tx0" "uart_tx" (slave ( "dev0" ) ""     #x14) (out "tx") (out "cs") (out "cl") (out "irq") (in "frstb") (in "fclk")) *place-list*)
(push '("debug0"   "debug"   (slave ( "dev0" ) ""     #x14) (in "in0" 31) (in "in1" 31) (out "out0" 31) (out "out1" 31) (in "boot")) *place-list*)
(push '("div0"     "div"     (slave ( "dev0" ) "c_"   #x14) (in "fclk") (in "scan_mode")) *place-list*)
(push '("mul0"     "mul"     (slave ( "dev0" ) "c_"   #x14) (in "fclk") (in "scan_mode")) *place-list*)
(push '("irq0"     "irq"     (slave ( "dev0" ) "c_"    #x4) (parms ".MSB(5)") (in "in" 5) (out "out")) *place-list*)
(push '("cpu0"     "rv32e"   (slave ( "dev0" ) "c_"   #x44) (parms ".main(1)")
        (master "d_" ("text0" 5) ("data0" 9) ("dev0" 9)) 
        (master "i_" ("text0" 9) ("data0" 5) ("dev0" 5)) 
        (in "hwsetb") (out "ret") (in "wakeup") (omux "halt")) 
      *place-list*)
(push '("ram1"     "sram1k"  (slave ( "data0" ) ""    #x400)) *place-list*)
;(push '("rom1"     "xipif"   (slave ( "text0" ) ""   #x8000000) (out "scl") (out "cs") (in "miso") (out "misoe") (out "mosi") (out "mosie")) *place-list*)
;(push '("ram0"     "sram1k"  (slave ( "text0" ) ""    #x400)) *place-list*)
(push '("rom0"     "srom8k"  (slave ( "text0" ) ""   #x2000)) *place-list*)
(synthesis 
  :tmp.v "/tmp/interconnect.v" 
  :interconnect.vh (string+ *prjroot*"/inc/interconnect.vh") 
  :pannel.h (string+ *prjroot*"/bus/include/pannel.h") 
  :pannel-in-bus-list '("dev0")
  :first-ram "data0_ram1_"
  :last-ram "data0_ram1_"
  :bus.ld (string+ *prjroot*"/bus/script/bus.ld")
  :bus.h (string+ *prjroot*"/bus/include/bus.h")
  )
