set_location_assignment PIN_T2  -to CLK
set_location_assignment PIN_D2  -to RSTB
set_location_assignment PIN_W1  -to BOOT
set_location_assignment PIN_V1  -to TEST
set_location_assignment PIN_C1  -to PAD[0]
set_location_assignment PIN_A3  -to PAD[1]
set_location_assignment PIN_B5  -to PAD[2]
set_location_assignment PIN_E6  -to PAD[3]
set_location_assignment PIN_B6  -to PAD[4]
set_location_assignment PIN_B7  -to PAD[5]
set_location_assignment PIN_B8  -to PAD[6]
set_location_assignment PIN_A10  -to PAD[7]
set_location_assignment PIN_B1  -to PAD[8]
set_location_assignment PIN_C4  -to PAD[9]
set_location_assignment PIN_E5  -to PAD[10]
set_location_assignment PIN_C6  -to PAD[11]
set_location_assignment PIN_C8  -to PAD[12]
set_location_assignment PIN_B9  -to PAD[13]
set_location_assignment PIN_B10  -to PAD[14]
set_location_assignment PIN_C10  -to PAD[15]
