set_location_assignment PIN_91  -to CLK
set_location_assignment PIN_88  -to RSTB
set_location_assignment PIN_89  -to BOOT
set_location_assignment PIN_90  -to TEST
set_location_assignment PIN_11  -to PAD[0]
set_location_assignment PIN_84  -to PAD[1]
set_location_assignment PIN_80  -to PAD[2]
set_location_assignment PIN_76  -to PAD[3]
set_location_assignment PIN_10  -to PAD[4]
set_location_assignment PIN_72  -to PAD[5]
set_location_assignment PIN_70  -to PAD[6]
set_location_assignment PIN_68  -to PAD[7]
set_location_assignment PIN_66  -to PAD[8]
set_location_assignment PIN_64  -to PAD[9]
set_location_assignment PIN_59  -to PAD[10]
set_location_assignment PIN_55  -to PAD[11]
set_location_assignment PIN_53  -to PAD[12]
set_location_assignment PIN_51  -to PAD[13]
set_location_assignment PIN_49  -to PAD[14]
set_location_assignment PIN_44  -to PAD[15]
#set_location_assignment PIN_10  -to rx
#set_location_assignment PIN_11  -to tx
